main/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

todo/urls.py
# from django.urls import path
# from .views import todo_list,todo_add,todo_update,todo_delete

# urlpatterns = [
    
#     path('', todo_list,name="todo_list"),
#     path('add/',todo_add,name="todo_add"),
#     path('update/<int:pk>',todo_update,name="todo_update"),
#     path('delete/<int:pk>',todo_delete,name="todo_delete"),
# ]

from django.urls import path
from todo.views import TodoListView,TodoCreateView,TodoUpdateView,TodoDeleteView,TodoDetailView

urlpatterns = [
    path('', TodoListView.as_view(), name='todo_list'),
    path('add/', TodoCreateView.as_view(), name='todo_add'),
    path('update/<int:pk>', TodoUpdateView.as_view(), name='todo_update'),
    path('delete/<int:pk>', TodoDeleteView.as_view(), name='todo_delete'),
    path('detail/<int:pk>', TodoDetailView.as_view(), name='todo_detail'),
   
]

todo/models.py
from django.db import models

priority_choices=[
    (1,'High'),
    (2,'Medium'),
    (3,'Low'),
]
status_choices=[
    ('C','Completed'),
    ('P','Processing'),
    ('W','Waiting'),
]

class Todo(models.Model):
    title=models.CharField(max_length=100)
    desc=models.TextField()
    priority=models.SmallIntegerField(choices=priority_choices,default=1)
    # seçim 1,2,3 olacağı için small integer seçtik
    status=models.CharField(choices=status_choices,default='W',max_length=1)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Todo
# bu yapı serializers gibi
class TodoForm(forms.ModelForm):
    class Meta:
        model=Todo
        # fields="__all__"
        exclude=[]
        # çıkartmak istediğin fieldları yaz
        

todo/views.py
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from .models import Todo
from .forms import TodoForm
from django.urls import reverse_lazy


class TodoListView(ListView):
    model=Todo
    template_name = 'todo/list.html'

# ? create ve update işlemlerinde form gerekli oduğundan form_class=TodoForm satırını bu fonksiyonlarda çağırdık
class TodoCreateView(CreateView):
    model=Todo
    form_class=TodoForm
    template_name = 'todo/add.html'
    # todo/todo_form.html
    success_url=reverse_lazy('todo_list')
    
class TodoUpdateView(UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = 'todo/update.html'
    # todo/todo_update.html
    success_url = reverse_lazy('todo_list')
    
class TodoDeleteView(DeleteView):
    model=Todo
    template_name = 'todo/delete.html'
    # todo/todo_confirm_delete.html
    success_url = reverse_lazy('todo_list')
class TodoDetailView(DetailView):
    model = Todo
    template_name = 'todo/detail.html'
    # todo/todo_detail.html
    success_url = reverse_lazy('todo_list')
        

todo/templates/add.html
{% extends 'base.html' %} 
{% block title %} Add To-Do {% endblock %} 
{% block container %} 
{% block page_title %}
<h1>Welcome to Add To-Do</h1>
{% endblock %}


   <form action="" method="POST">
    {% csrf_token %}
    <table>{{form}}</table>
    <input type="submit" value="Add Todo"/>

   </form>





{% endblock container %} 

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Base HTML {% endblock %}</title>
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
</head>
<body>
    {% block container %}
    {% block page_title %}
  <h1>Welcome to base page</h1>
{% endblock %}

    {% endblock container %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/list.html
{% extends 'base.html' %}
{% block title %} List To-Do {% endblock %}
{% block extra_css %}
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
    }
    th {
      background-color: #f2f2f2;
    }
    tr:nth-child(even) {
      background-color: #f2f2f2;
    }
  </style>
{% endblock %}

{% block container %}
{% block page_title %}
  <h1>Welcome to list</h1>
{% endblock %}



  
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Priority</th>
        <th>Status</th>
        <th>Created Date</th>
        <th>Updated Date</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
        <tr>
          <td>{{ todo.title }}</td>
          <td>{{ todo.desc }}</td>
          <td>{{ todo.get_priority_display }}</td>
          <td>{{ todo.get_status_display }}</td>
          <td>{{ todo.created_date }}</td>
          <td>{{ todo.updated_date }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="6">No todos found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

    {% endblock container %}

{% comment %} ? get_priority_display ve get_status_display metodları, öncelik ve durum alanlarındaki seçenek değerlerinin anlamlı şekilde görüntülenmesini sağlamak için kullanılır. {% endcomment %}

todo/templates/todo/add.html
{% extends 'base.html' %} 
{% block title %} Add To-Do {% endblock %} 
{% block container %} 
{% block page_title %}
<h1>Welcome to Add To-Do</h1>
{% endblock %}


   <form action="" method="POST">
    {% csrf_token %}
    <table>{{form}}</table>
    <input type="submit" value="Add Todo"/>

   </form>





{% endblock container %} 

todo/templates/todo/delete.html
{% extends 'base.html' %} 
{% block title %} Update To-Do {% endblock %} 
{% block container %} 
{% block page_title %}
<h1>Update To-Do</h1>
{% endblock %}
{% comment %}! Bu sayfaya çokta gerek yok ! {% endcomment %}

   <form action="" method="POST">
    {% csrf_token %}
    
    <input type="submit" value="Delete Todo"/>

   </form>





{% endblock container %} 

todo/templates/todo/detail.html
{% extends 'base.html' %}
{% block container %}

<hr>
<h2>TodoDetailView</h2>
<p><a href="/" class="btn btn-primary">LIST</a></p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>priority</th>
            <th>title</th>
            <th>created_date</th>
            <th>status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                {% if todo.priority == 1 %}
                <b class="text-danger">{{ todo.get_priority_display }}</b>
                {% elif todo.priority == 2 %}
                <b class="text-warning">{{ todo.get_priority_display }}</b>
                {% else %}
                <b class="text-info">{{ todo.get_priority_display }}</b>
                {% endif %}
            </td>
            <td>{{ todo.title }}</td>
            <td>{{ todo.created_date }}</td>
            <td>
                {% if todo.status == "P" %}
                <b class="text-danger">{{ todo.get_status_display }}</b>
                {% else %}
                <b class="text-success">{{ todo.get_status_display }}</b>
                {% endif %}
            </td>
            <td>
                | <a href="/update/{{ todo.id }}">Update</a>
                | <a href="/delete/{{ todo.id }}" onclick="return confirm('Are you sure?')">Sil</a>
            </td>
        </tr>
    </tbody>
</table>
<b>Description:</b> <br> {{ todo.description }}
<hr>
<b>Add:</b> <br> {{ todo.created_date }}
<b>Update:</b> <br> {{ todo.updated_date }}

{% endblock container %}

todo/templates/todo/list.html
{% extends 'base.html' %} 
{% block title %} List To-Do {% endblock %} 
{% block container %} 
{% block page_title %}
<h1>Welcome to list</h1>
{% endblock %}
<a href="/add" class="btn btn-primary">Add Todo</a>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Created Date</th>
      <th>Updated Date</th>
    </tr>
  </thead>
  <tbody>
    {% for todo in object_list %}
    <tr>
      <td>{{ todo.title }}</td>
      <td>{{ todo.desc }}</td>
      
    
      <td>

                    
                    {% comment %} {% if todo.priority == 1 %}
                    <b class="text-danger">{{todo.get_priority_display}}</b> 
                    {% elif  todo.priority == 2 %}
                    <b class="text-warning">{{todo.get_priority_display}}</b>  
                    {% else %}
                    <b class="text-info">{{todo.get_priority_display}}</b> 
                    {% endif %} {% endcomment %}
                     <b class="{% if todo.priority == 1 %}text-danger{% elif todo.priority == 2 %}text-warning{% else %}text-info{% endif %}">
                     {{ todo.get_priority_display }}
                    </b> 
                   
                     
                </td>
      
       
      <td > <b class="{% if todo.status == 'C' %}text-danger{% elif todo.status == 'P' %}text-warning{% else %}text-info{% endif %}">
                     
                    {{ todo.get_status_display }}</b></td>
      <td>{{ todo.created_date }}</td>
      <td>{{ todo.updated_date }}</td>
      <td><a href="update/{{todo.id}}">Update</a> <a href="delete/{{todo.id}}" >Delete </a><a href="detail/{{todo.id}}" >Detail</a> </td>
      {% comment %} onclick="return confirm('are you sure ?')" {% endcomment %}
      
        
      <
    </tr>
    {% empty %}
    <tr>
      <td colspan="6">No todos found.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock container %} 

todo/templates/todo/update.html
{% extends 'base.html' %} 
{% block title %} Update To-Do {% endblock %} 
{% block container %} 
{% block page_title %}
<h1>Update To-Do</h1>
{% endblock %}


   <form action="" method="POST">
    {% csrf_token %}
    <table>{{form}}</table>
    <input type="submit" value="Update Todo"/>

   </form>





{% endblock container %} 

todo/templates/update.html
{% extends 'base.html' %} 
{% block title %} Update To-Do {% endblock %} 
{% block container %} 
{% block page_title %}
<h1>Update To-Do</h1>
{% endblock %}


   <form action="" method="POST">
    {% csrf_token %}
    <table>{{form}}</table>
    <input type="submit" value="Update Todo"/>

   </form>





{% endblock container %} 